Update pipeline-basico.yml

diff --git a/.github/workflows/pipeline-basico.yml b/.github/workflows/pipeline-basico.yml
--- a/.github/workflows/pipeline-basico.yml
+++ b/.github/workflows/pipeline-basico.yml
@@ -13,9 +13,8 @@ jobs:
 
       - name: Validar archivos
         run: |
-          echo "Iniciando validación..."
-          sleep 5
-          echo "Validación terminada correctamente"
+          echo "Se encontró un error"
+          exit 1
 
   probar:
     runs-on: ubuntu-latest
